In [1]:
import kagglehub
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Dataset Load and Overview

In [2]:
# Download latest version
path = kagglehub.dataset_download("yeanzc/telco-customer-churn-ibm-dataset")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/yeanzc/telco-customer-churn-ibm-dataset?dataset_version_number=1...

100%|██████████| 1.25M/1.25M [00:00<00:00, 101MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/yeanzc/telco-customer-churn-ibm-dataset/versions/1

In [3]:
df = pd.read_excel("/root/.cache/kagglehub/datasets/yeanzc/telco-customer-churn-ibm-dataset/versions/1/Telco_customer_churn.xlsx")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [11]:
print(df.duplicated(subset='CustomerID').sum())

0

In [12]:
print(df.columns)

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [4]:
# prompt: skrip untuk mengambil kolom kategorikal saja

categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("Kolom Kategorikal:")
categorical_cols

Kolom Kategorikal:

Index(['CustomerID', 'Country', 'State', 'City', 'Lat Long', 'Gender',
       'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Total Charges', 'Churn Label', 'Churn Reason'],
      dtype='object')

In [13]:
# prompt: skrip untuk mengambil kolom kategorikal saja

categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("Kolom Kategorikal:")
display(categorical_cols)

# Select the categorical columns from the DataFrame and calculate the number of unique values
df_cat_unique_counts = df[categorical_cols].nunique()
print("\nJumlah Nilai Unik per Kolom Kategorikal:")
display(df_cat_unique_counts)

Kolom Kategorikal:

Index(['CustomerID', 'Country', 'State', 'City', 'Lat Long', 'Gender',
       'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Total Charges', 'Churn Label', 'Churn Reason'],
      dtype='object')

Jumlah Nilai Unik per Kolom Kategorikal:

CustomerID           7043
Country                 1
State                   1
City                 1129
Lat Long             1652
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Total Charges        6531
Churn Label             2
Churn Reason           20
dtype: int64

In [16]:
#Check if the categorical variables have appropriate levels
for col in categorical_cols:
    print(col.upper(), ":", df[col].unique())

CUSTOMERID : ['3668-QPYBK' '9237-HQITU' '9305-CDSKC' ... '2234-XADUH' '4801-JZAZL'
 '3186-AJIEK']
COUNTRY : ['United States']
STATE : ['California']
CITY : ['Los Angeles' 'Beverly Hills' 'Huntington Park' ... 'Standish' 'Tulelake'
 'Olympic Valley']
LAT LONG : ['33.964131, -118.272783' '34.059281, -118.30742' '34.048013, -118.293953'
 ... '40.346634, -120.386422' '41.813521, -121.492666'
 '39.191797, -120.212401']
GENDER : ['Male' 'Female']
SENIOR CITIZEN : ['No' 'Yes']
PARTNER : ['No' 'Yes']
DEPENDENTS : ['No' 'Yes']
PHONE SERVICE : ['Yes' 'No']
MULTIPLE LINES : ['No' 'Yes' 'No phone service']
INTERNET SERVICE : ['DSL' 'Fiber optic' 'No']
ONLINE SECURITY : ['Yes' 'No' 'No internet service']
ONLINE BACKUP : ['Yes' 'No' 'No internet service']
DEVICE PROTECTION : ['No' 'Yes' 'No internet service']
TECH SUPPORT : ['No' 'Yes' 'No internet service']
STREAMING TV : ['No' 'Yes' 'No internet service']
STREAMING MOVIES : ['No' 'Yes' 'No internet service']
CONTRACT : ['Month-to-month' 'Two year' 'One year']
PAPERLESS BILLING : ['Yes' 'No']
PAYMENT METHOD : ['Mailed check' 'Electronic check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TOTAL CHARGES : [108.15 151.65 820.5 ... 7362.9 346.45 6844.5]
CHURN LABEL : ['Yes' 'No']
CHURN REASON : ['Competitor made better offer' 'Moved' 'Competitor had better devices'
 'Competitor offered higher download speeds'
 'Competitor offered more data' 'Price too high' 'Product dissatisfaction'
 'Service dissatisfaction' 'Lack of self-service on Website'
 'Network reliability' 'Limited range of services'
 'Lack of affordable download/upload speed' 'Long distance charges'
 'Extra data charges' "Don't know" 'Poor expertise of online support'
 'Poor expertise of phone support' 'Attitude of service provider'
 'Attitude of support person' 'Deceased' nan]

In [17]:
df.isna().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

#Data Cleansing

In [10]:
df_clean = df.copy()

In [8]:
print(f"Missing values before cleaning: {df_clean.isnull().sum().sum()}")

Missing values before cleaning: 5174

In [16]:
# 1. Convert TotalCharges to numeric if it's stored as string
if 'Total Charges' in df_clean.columns:
    df_clean['Total Charges'] = pd.to_numeric(df_clean['Total Charges'], errors='coerce')

In [24]:
 # 2. Handle missing values in Total Charges (common issue)
if 'Total Charges' in df_clean.columns and df_clean['Total Charges'].isnull().sum() > 0:
    # Fill missing TotalCharges with 0 for new customers or calculate from tenure and monthly charges
    if 'Tenure Months' in df_clean.columns and 'Monthly Charges' in df_clean.columns:
        df_clean['Total Charges'] = df_clean['Total Charges'].fillna(
            df_clean['Tenure Months'] * df_clean['Monthly Charges']
        )
    else:
        df_clean['Total Charges'] = df_clean['Total Charges'].fillna(0)

In [31]:
# 3. Standardize Yes/No columns
yes_no_cols = []
for col in df_clean.columns:
    if df_clean[col].dtype == 'object':
        unique_vals = df_clean[col].unique()
        if len(unique_vals) == 2 and set(unique_vals) == {'Yes', 'No'}:
            yes_no_cols.append(col)
print(f"Yes/No columns found: {yes_no_cols}")

Yes/No columns found: ['Senior Citizen', 'Partner', 'Dependents', 'Phone Service', 'Paperless Billing', 'Churn Label']

In [33]:
 # 4. Handle categorical variables - ensure consistent formatting
categorical_cols = df_clean.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df_clean[col] = df_clean[col].str.strip()  # Remove whitespace

Missing values after cleaning: 5174

In [35]:
# 3. Handle Churn Reason column (CRITICAL DECISION)
churn_reason_cols = [col for col in df_clean.columns if 'reason' in col.lower() or 'churn' in col.lower()]

print(f"\nChurn-related columns found: {churn_reason_cols}")

Churn-related columns found: ['Churn Label', 'Churn Value', 'Churn Score', 'Churn Reason']

In [38]:
# BUSINESS DECISION: Keep churn reason column for churned customers analysis
# This is valuable for understanding WHY customers churn
for col in churn_reason_cols:
    if col in df_clean.columns and col.lower() != 'churn':
        missing_count = df_clean[col].isnull().sum()
        churned_count = (df_clean['Churn'] == 'Yes').sum() if 'Churn' in df_clean.columns else 0

        print(f"\n🔍 CHURN REASON ANALYSIS:")
        print(f"  Column: {col}")
        print(f"  Missing values: {missing_count}")
        print(f"  Churned customers: {churned_count}")
        print(f"  Expected missing: {len(df_clean) - churned_count} (non-churned customers)")

🔍 CHURN REASON ANALYSIS:
  Column: Churn Label
  Missing values: 0
  Churned customers: 0
  Expected missing: 7043 (non-churned customers)

🔍 CHURN REASON ANALYSIS:
  Column: Churn Value
  Missing values: 0
  Churned customers: 0
  Expected missing: 7043 (non-churned customers)

🔍 CHURN REASON ANALYSIS:
  Column: Churn Score
  Missing values: 0
  Churned customers: 0
  Expected missing: 7043 (non-churned customers)

🔍 CHURN REASON ANALYSIS:
  Column: Churn Reason
  Missing values: 5174
  Churned customers: 0
  Expected missing: 7043 (non-churned customers)

In [40]:
# Verify that missing values correspond to non-churned customers
if 'Churn' in df_clean.columns:
    non_churned_with_reason = df_clean[(df_clean['Churn'] == 'No') & (df_clean[col].notna())].shape[0]
    churned_without_reason = df_clean[(df_clean['Churn'] == 'Yes') & (df_clean[col].isna())].shape[0]

    print(f"  Non-churned customers with reason: {non_churned_with_reason}")
    print(f"  Churned customers without reason: {churned_without_reason}")

    # DECISION: Keep the column, missing values are expected for retained customers
    if missing_count > 0:
        print(f"  ✅ KEEPING {col} - Missing values are expected for retained customers")
        print(f"  ✅ Will use for churn reason analysis among churned customers only")

        # Optional: Fill missing values with "Not Applicable" for clarity
        # df_clean[col] = df_clean[col].fillna('Not Applicable - Customer Retained')

In [42]:
# Ensure 'Churn Label' and 'Churn Reason' columns exist
if 'Churn Label' in df_clean.columns and 'Churn Reason' in df_clean.columns:
    # Identify rows where 'Churn Label' is 'No' and 'Churn Reason' is null
    condition = (df_clean['Churn Label'] == 'No') & (df_clean['Churn Reason'].isnull())

    # Fill the 'Churn Reason' with 'No Churn' for these specific rows
    df_clean.loc[condition, 'Churn Reason'] = 'No Churn'

    print("\nFilling null 'Churn Reason' with 'No Churn' for 'Churn Label' == 'No':")
    # Verify the changes - check null counts in 'Churn Reason' again
    print(df_clean.isna().sum()['Churn Reason'])

    # Optionally, check a sample of rows where this change was made
    # print("\nSample rows after filling nulls:")
    # display(df_clean[condition].head())
else:
    print("Columns 'Churn Label' or 'Churn Reason' not found in the DataFrame.")

Filling null 'Churn Reason' with 'No Churn' for 'Churn Label' == 'No':
0

In [52]:
df_clean.columns = df_clean.columns.str.replace(' ', '_')
df_clean.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip_Code',
       'Lat_Long', 'Latitude', 'Longitude', 'Gender', 'Senior_Citizen',
       'Partner', 'Dependents', 'Tenure_Months', 'Phone_Service',
       'Multiple_Lines', 'Internet_Service', 'Online_Security',
       'Online_Backup', 'Device_Protection', 'Tech_Support', 'Streaming_TV',
       'Streaming_Movies', 'Contract', 'Paperless_Billing', 'Payment_Method',
       'Monthly_Charges', 'Total_Charges', 'Churn_Label', 'Churn_Value',
       'Churn_Score', 'CLTV', 'Churn_Reason'],
      dtype='object')

#Feature Engineering

In [88]:
# 1. Tenure Categories (Year)
if 'Tenure_Months' in df_clean.columns:
    df_clean['Tenure_Category'] = pd.cut(
        df_clean['Tenure_Months'],
        bins=[0, 12, 24, 48, 72],
        labels=['0-1 Year', '1-2 Years', '2-4 Years', '4-6 Years'],
        right=True
    )
    df_clean.loc[df_clean['Tenure_Months'] == 0, 'Tenure_Category'] = '0-1 Year'

print("\nAdding 'Tenure_Category' column:")
print(df_clean[['Tenure_Months', 'Tenure_Category']].head())
print("\nValue Counts for 'Tenure_Category':")
print(df_clean['Tenure_Category'].value_counts())

Adding 'Tenure_Category' column:
   Tenure_Months Tenure_Category
0              2        0-1 Year
1              2        0-1 Year
2              8        0-1 Year
3             28       2-4 Years
4             49       4-6 Years

Value Counts for 'Tenure_Category':
Tenure_Category
4-6 Years    2239
0-1 Year     2186
2-4 Years    1594
1-2 Years    1024
Name: count, dtype: int64

In [54]:
# 2. Monthly Charges Categories
if 'Monthly_Charges' in df_clean.columns:
    df_clean['monthly_charges_category'] = pd.cut(
          df_clean['Monthly_Charges'],
        bins=[0, 35, 50, 65, 80, float('inf')],
        labels=['Low ($0-35)', 'Medium-Low ($35-50)', 'Medium ($50-65)', 'Medium-High ($65-80)', 'High ($80+)']
    )

In [55]:
# 3. Service Usage Score (count of services used)
service_cols = [col for col in df_clean.columns if col in [
      'Phone_Service', 'Multiple_Lines', 'Internet_Service', 'Online_Security',
    'Online_Backup', 'Device_Protection', 'Tech_Support', 'Streaming_TV', 'Streaming_Movies'
]]
if service_cols:
    df_clean['service_usage_score'] = 0
    for col in service_cols:
        if col in df_clean.columns:
            df_clean['service_usage_score'] += (df_clean[col] == 'Yes').astype(int)

In [57]:
# 4. Customer Value Score (based on tenure and charges)
if 'Tenure_Months' in df_clean.columns and 'Monthly_Charges' in df_clean.columns:
    df_clean['customer_value_score'] = (
        (df_clean['Tenure_Months'] / df_clean['Tenure_Months'].max()) * 0.4 +
        (df_clean['Monthly_Charges'] / df_clean['Monthly_Charges'].max()) * 0.6
    ) * 100

In [59]:
# 5. Risk Categories
if 'Contract' in df_clean.columns and 'Payment_Method' in df_clean.columns:
    df_clean['risk_category'] = 'Medium'
    df_clean.loc[
        (df_clean['Contract'] == 'Month-to-month') &
        (df_clean['Payment_Method'] == 'Electronic check'),
        'risk_category'
    ] = 'High'
    df_clean.loc[
        (df_clean['Contract'].isin(['One year', 'Two year'])) &
        (df_clean['Payment_Method'] != 'Electronic check'),
        'risk_category'
    ] = 'Low'

In [60]:
# 6. Average Monthly Charges per Service
if 'Monthly_Charges' in df_clean.columns and 'service_usage_score' in df_clean.columns:
    df_clean['avg_charge_per_service'] = np.where(
          df_clean['service_usage_score'] > 0,
        df_clean['Monthly_Charges'] / df_clean['service_usage_score'],
        df_clean['Monthly_Charges']
    )

In [79]:
 # 7. Senior Customer Flag
if 'Senior_Citizen' in df_clean.columns:
    df_clean['is_senior'] = df_clean['Senior_Citizen'].map({'Yes': 1, 'No': 0})

In [82]:
df_clean

,CustomerID,Count,Country,State,City,Zip_Code,Lat_Long,Latitude,Longitude,Gender,...,CLTV,Churn_Reason,Tenure_Category,monthly_charges_category,service_usage_score,customer_value_score,risk_category,avg_charge_per_service,is_senior,churn_category
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,3239,Competitor made better offer,0-1 Year,Medium ($50-65),3,28.319532,Medium,17.950000,0,Competitive Offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,2701,Moved,0-1 Year,Medium-High ($65-80),1,36.833216,High,70.700000,0,Relocation
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,5372,Moved,0-1 Year,High ($80+),5,54.793918,High,19.930000,0,Relocation
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,5003,Moved,2-4 Years,High ($80+),6,68.507135,High,17.466667,0,Relocation
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,5340,Competitor had better devices,4-6 Years,High ($80+),6,79.618012,Medium,17.283333,0,Competitive Offer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,5306,No Churn,4-6 Years,Low ($0-35),1,50.686316,Low,21.150000,0,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,2140,No Churn,1-2 Years,High ($80+),7,56.179649,Low,12.114286,0,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,5560,No Churn,4-6 Years,High ($80+),6,92.143158,Low,17.200000,0,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,2793,No Churn,0-1 Year,Low ($0-35),1,21.066901,High,29.600000,0,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,5097,No Churn,4-6 Years,High ($80+),6,90.047719,Low,17.608333,0,NaN

#Key Insights

In [ ]:
# prompt: buat skrip untuk mengisi nilai null pada kolom churn_Category. sesuaikan dengan churn_label

# Isi nilai null pada Churn_Category berdasarkan Churn_Label
# Jika Churn_Label adalah 'No', maka Churn_Category seharusnya null (atau 'No Churn')
# Jika Churn_Label adalah 'Yes', maka Churn_Category seharusnya terisi

if 'Churn_Label' in df_clean.columns and 'Churn_Category' in df_clean.columns:
    # Filter baris di mana Churn_Label adalah 'No' dan Churn_Category adalah null
    condition_fill_no = (df_clean['Churn_Label'] == 'No') & (df_clean['Churn_Category'].isnull())
    # Isi Churn_Category dengan nilai 'No Churn' untuk baris yang memenuhi kondisi
    df_clean.loc[condition_fill_no, 'Churn_Category'] = 'No Churn'

    # Kita juga bisa memeriksa apakah ada baris Churn_Label 'Yes' yang Churn_Categorynya null
    # Jika ada, ini mungkin data yang perlu diperbaiki atau diinvestigasi lebih lanjut.
    # Namun, berdasar deskripsi, fokusnya adalah mengisi null saat Churn_Label 'No'.

    print("\nMengisi null pada 'Churn_Category' berdasarkan 'Churn_Label':")
    print(f"Jumlah null di 'Churn_Category' sebelum diisi: {df_clean['Churn_Category'].isnull().sum()}")

    # Verifikasi pengisian
    # Cek jumlah null di Churn_Category setelah diisi
    print(f"Jumlah null di 'Churn_Category' setelah diisi: {df_clean['Churn_Category'].isnull().sum()}")

    # Tampilkan contoh baris yang Churn_Labelnya 'No'
    print("\nContoh baris dengan 'Churn_Label' == 'No' dan 'Churn_Category' terisi:")
    display(df_clean[df_clean['Churn_Label'] == 'No'][['Churn_Label', 'Churn_Category']].head())

    # Cek apakah ada baris 'Churn_Label' == 'Yes' yang 'Churn_Category' nya masih null
    if df_clean[(df_clean['Churn_Label'] == 'Yes') & (df_clean['Churn_Category'].isnull())].shape[0] > 0:
        print("\nPERINGATAN: Ada baris dengan 'Churn_Label' == 'Yes' yang 'Churn_Category'-nya masih null.")
        print("Anda mungkin perlu menangani baris ini secara terpisah (misal: mengisi dengan 'Unknown' atau 'Other').")
else:
    print("Kolom 'Churn_Label' atau 'Churn_Category' tidak ditemukan di DataFrame.")

```

In [95]:
# Churn Analysis
churn_col = 'Churn_Label' if 'Churn_Label' in df_clean.columns else 'Churn'
if churn_col in df_clean.columns:
    churn_rate = (df_clean[churn_col] == 'Yes').mean()
    print(f"\n📊 OVERALL CHURN METRICS:")
    print(f"Total Customers: {len(df_clean):,}")
    print(f"Churned Customers: {(df_clean[churn_col] == 'Yes').sum():,}")
    print(f"Overall Churn Rate: {churn_rate:.2%}")

    # Churn Reason Analysis (if available)
    if 'Churn_Reason' in df_clean.columns:
        churned_customers = df_clean[df_clean[churn_col] == 'Yes']
        churn_reasons = churned_customers['Churn_Reason'].value_counts()

        print(f"\n🎯 CHURN REASON ANALYSIS:")
        print(f"Top reasons for customer churn:")
        for i, (reason, count) in enumerate(churn_reasons.head(10).items(), 1):
            percentage = (count / len(churned_customers)) * 100
            print(f"  {i}. {reason}: {count} customers ({percentage:.1f}%)")

        # Group churn reasons into categories for strategic analysis
        churn_categories = {}
        for reason in churn_reasons.index:
            reason_lower = reason.lower()
            if any(word in reason_lower for word in ['price', 'expensive', 'cost', 'bill']):
                churn_categories[reason] = 'Price/Cost Issues'
            elif any(word in reason_lower for word in ['competitor', 'better', 'offer']):
                churn_categories[reason] = 'Competitive Offer'
            elif any(word in reason_lower for word in ['service', 'quality', 'poor', 'bad']):
                churn_categories[reason] = 'Service Quality'
            elif any(word in reason_lower for word in ['support', 'customer', 'help']):
                churn_categories[reason] = 'Customer Support'
            elif any(word in reason_lower for word in ['moved', 'relocation', 'location']):
                churn_categories[reason] = 'Relocation'
            elif any(word in reason_lower for word in ['no', 'churn']):
                churn_categories[reason] = 'Active Customer'
            else:
                churn_categories[reason] = 'Other'

        # Add churn category column
        df_clean['churn_category'] = df_clean['Churn_Reason'].map(churn_categories)

        # Add No Churn to Customer who choose No
        if 'Churn_Label' in df_clean.columns and 'churn_category' in df_clean.columns:
          condition_fill_no = (df_clean['Churn_Label'] == 'No') & (df_clean['churn_category'].isnull())
          df_clean.loc[condition_fill_no, 'churn_category'] = 'No Churn'

        # Analyze churn categories
        category_analysis = df_clean[df_clean[churn_col] == 'Yes']['churn_category'].value_counts()
        print(f"\n📋 CHURN CATEGORIES:")
        for category, count in category_analysis.items():
            if category != 'Active Customer':
                percentage = (count / len(churned_customers)) * 100
                print(f"  {category}: {count} customers ({percentage:.1f}%)")

    # Churn by key factors
    print(f"\n📈 CHURN BY KEY FACTORS:")

    # By Contract Type
    if 'Contract' in df_clean.columns:
        contract_churn = df_clean.groupby('Contract')[churn_col].apply(
            lambda x: (x == 'Yes').mean()
        ).sort_values(ascending=False)
        print(f"\nChurn by Contract Type:")
        for contract, rate in contract_churn.items():
            print(f"  {contract}: {rate:.2%}")

    # By Tenure Category
    if 'Tenure_Category' in df_clean.columns:
        tenure_churn = df_clean.groupby('Tenure_Category')[churn_col].apply(
            lambda x: (x == 'Yes').mean()
        ).sort_values(ascending=False)
        print(f"\nChurn by Tenure Category:")
        for tenure, rate in tenure_churn.items():
            print(f"  {tenure}: {rate:.2%}")

    # By Payment Method
    if 'Payment_Method' in df_clean.columns:
        payment_churn = df_clean.groupby('Payment_Method')[churn_col].apply(
            lambda x: (x == 'Yes').mean()
        ).sort_values(ascending=False)
        print(f"\nChurn by Payment Method:")
        for payment, rate in payment_churn.items():
            print(f"  {payment}: {rate:.2%}")

    # By Risk Category
    if 'risk_category' in df_clean.columns:
        risk_churn = df_clean.groupby('risk_category')[churn_col].apply(
            lambda x: (x == 'Yes').mean()
        ).sort_values(ascending=False)
        print(f"\nChurn by Risk Category:")
        for risk, rate in risk_churn.items():
            print(f"  {risk}: {rate:.2%}")

📊 OVERALL CHURN METRICS:
Total Customers: 7,043
Churned Customers: 1,869
Overall Churn Rate: 26.54%

🎯 CHURN REASON ANALYSIS:
Top reasons for customer churn:
  1. Attitude of support person: 192 customers (10.3%)
  2. Competitor offered higher download speeds: 189 customers (10.1%)
  3. Competitor offered more data: 162 customers (8.7%)
  4. Don't know: 154 customers (8.2%)
  5. Competitor made better offer: 140 customers (7.5%)
  6. Attitude of service provider: 135 customers (7.2%)
  7. Competitor had better devices: 130 customers (7.0%)
  8. Network reliability: 103 customers (5.5%)
  9. Product dissatisfaction: 102 customers (5.5%)
  10. Price too high: 98 customers (5.2%)

📋 CHURN CATEGORIES:
  Competitive Offer: 621 customers (33.2%)
  Service Quality: 395 customers (21.1%)
  Other: 356 customers (19.0%)
  Customer Support: 192 customers (10.3%)
  Price/Cost Issues: 98 customers (5.2%)
  Relocation: 53 customers (2.8%)

📈 CHURN BY KEY FACTORS:

Churn by Contract Type:
  Month-to-month: 42.71%
  One year: 11.27%
  Two year: 2.83%

Churn by Tenure Category:
  0-1 Year: 47.44%
  1-2 Years: 28.71%
  2-4 Years: 20.39%
  4-6 Years: 9.51%

Churn by Payment Method:
  Electronic check: 45.29%
  Mailed check: 19.11%
  Bank transfer (automatic): 16.71%
  Credit card (automatic): 15.24%

Churn by Risk Category:
  High: 53.73%
  Medium: 29.06%
  Low: 5.16%

/tmp/ipython-input-95-99929913.py:70: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tenure_churn = df_clean.groupby('Tenure_Category')[churn_col].apply(

In [64]:
# Revenue Analysis
if 'Monthly_Charges' in df_clean.columns and churn_col in df_clean.columns:
    print(f"\n💰 REVENUE IMPACT ANALYSIS:")
    churned_revenue = df_clean[df_clean[churn_col] == 'Yes']['Monthly_Charges'].sum()
    retained_revenue = df_clean[df_clean[churn_col] == 'No']['Monthly_Charges'].sum()
    total_revenue = churned_revenue + retained_revenue

    print(f"Monthly Revenue Lost to Churn: ${churned_revenue:,.2f}")
    print(f"Monthly Revenue Retained: ${retained_revenue:,.2f}")
    print(f"Revenue at Risk: {(churned_revenue/total_revenue):.2%}")

    # Annual impact
    annual_lost_revenue = churned_revenue * 12
    print(f"Estimated Annual Revenue Lost: ${annual_lost_revenue:,.2f}")

    # Revenue impact by churn category
    if 'churn_category' in df_clean.columns:
        print(f"\n💸 REVENUE IMPACT BY CHURN CATEGORY:")
        churn_revenue_by_category = df_clean[df_clean[churn_col] == 'Yes'].groupby('churn_category')['Monthly_Charges'].sum().sort_values(ascending=False)
        for category, revenue in churn_revenue_by_category.items():
            if category != 'Active Customer':
                annual_impact = revenue * 12
                print(f"  {category}: ${revenue:,.2f}/month (${annual_impact:,.2f}/year)")

💰 REVENUE IMPACT ANALYSIS:
Monthly Revenue Lost to Churn: $139,130.85
Monthly Revenue Retained: $316,985.75
Revenue at Risk: 30.50%
Estimated Annual Revenue Lost: $1,669,570.20

💸 REVENUE IMPACT BY CHURN CATEGORY:
  Competitive Offer: $46,600.80/month ($559,209.60/year)
  Service Quality: $29,307.40/month ($351,688.80/year)
  Other: $26,613.20/month ($319,358.40/year)
  Customer Support: $13,980.85/month ($167,770.20/year)
  Price/Cost Issues: $7,398.55/month ($88,782.60/year)
  Relocation: $4,131.00/month ($49,572.00/year)

In [65]:
# Customer Segmentation Analysis
if 'customer_value_score' in df_clean.columns and churn_col in df_clean.columns:
    print(f"\n🎯 CUSTOMER SEGMENTATION INSIGHTS:")

    # High-value customers at risk
    high_value_threshold = df_clean['customer_value_score'].quantile(0.8)
    high_value_customers = df_clean[df_clean['customer_value_score'] >= high_value_threshold]
    high_value_churn_rate = (high_value_customers[churn_col] == 'Yes').mean()

    print(f"High-Value Customer Churn Rate: {high_value_churn_rate:.2%}")
    print(f"High-Value Customers at Risk: {(high_value_customers[churn_col] == 'Yes').sum():,}")

    # Service usage impact
    if 'service_usage_score' in df_clean.columns:
        service_churn = df_clean.groupby('service_usage_score')[churn_col].apply(
            lambda x: (x == 'Yes').mean()
        )
        print(f"\nChurn by Service Usage Score:")
        for score, rate in service_churn.items():
            print(f"  {score} services: {rate:.2%}")

🎯 CUSTOMER SEGMENTATION INSIGHTS:
High-Value Customer Churn Rate: 15.47%
High-Value Customers at Risk: 218

Churn by Service Usage Score:
  0 services: 43.75%
  1 services: 21.11%
  2 services: 32.83%
  3 services: 36.48%
  4 services: 31.34%
  5 services: 25.55%
  6 services: 22.49%
  7 services: 12.41%
  8 services: 5.29%

#Strategic Recommendation

In [66]:
recommendations = []

# Churn reason-based recommendations
if 'churn_category' in df_clean.columns and churn_col in df_clean.columns:
    category_analysis = df_clean[df_clean[churn_col] == 'Yes']['churn_category'].value_counts()

    # Price/Cost Issues
    if 'Price/Cost Issues' in category_analysis.index:
        price_churn_pct = (category_analysis['Price/Cost Issues'] / len(df_clean[df_clean[churn_col] == 'Yes'])) * 100
        if price_churn_pct > 20:
            recommendations.append({
                'priority': 'HIGH',
                'area': 'Pricing Strategy',
                'recommendation': 'Implement competitive pricing and value communication program',
                'details': f'{price_churn_pct:.1f}% of churn is due to price/cost issues. Develop retention pricing tiers and value proposition messaging.',
                'expected_impact': '20-30% reduction in price-related churn'
            })

    # Competitive Offer
    if 'Competitive Offer' in category_analysis.index:
        comp_churn_pct = (category_analysis['Competitive Offer'] / len(df_clean[df_clean[churn_col] == 'Yes'])) * 100
        if comp_churn_pct > 15:
            recommendations.append({
                'priority': 'HIGH',
                'area': 'Competitive Intelligence',
                'recommendation': 'Enhance competitive monitoring and counter-offer programs',
                'details': f'{comp_churn_pct:.1f}% of churn is due to competitive offers. Implement win-back campaigns and competitive matching.',
                'expected_impact': '15-25% reduction in competitive churn'
            })

    # Service Quality
    if 'Service Quality' in category_analysis.index:
        quality_churn_pct = (category_analysis['Service Quality'] / len(df_clean[df_clean[churn_col] == 'Yes'])) * 100
        if quality_churn_pct > 10:
            recommendations.append({
                'priority': 'HIGH',
                'area': 'Service Quality',
                'recommendation': 'Implement comprehensive service quality improvement program',
                'details': f'{quality_churn_pct:.1f}% of churn is due to service quality issues. Focus on network improvements and reliability.',
                'expected_impact': '25-35% reduction in quality-related churn'
            })

    # Customer Support
    if 'Customer Support' in category_analysis.index:
        support_churn_pct = (category_analysis['Customer Support'] / len(df_clean[df_clean[churn_col] == 'Yes'])) * 100
        if support_churn_pct > 5:
            recommendations.append({
                'priority': 'MEDIUM',
                'area': 'Customer Support',
                'recommendation': 'Enhance customer support experience and training',
                'details': f'{support_churn_pct:.1f}% of churn is due to customer support issues. Improve response times and resolution quality.',
                'expected_impact': '30-40% reduction in support-related churn'
            })

In [67]:
# Contract-based recommendations
if 'Contract' in df_clean.columns and churn_col in df_clean.columns:
    month_to_month_churn = df_clean[df_clean['Contract'] == 'Month-to-month'][churn_col].apply(
        lambda x: x == 'Yes'
    ).mean()

    if month_to_month_churn > 0.4:  # If > 40% churn
        recommendations.append({
            'priority': 'HIGH',
            'area': 'Contract Strategy',
            'recommendation': 'Implement contract incentive programs',
            'details': f'Month-to-month customers have {month_to_month_churn:.1%} churn rate. Offer discounts for annual contracts.',
            'expected_impact': '15-25% churn reduction'
        })

In [68]:
# Payment method recommendations
if 'Payment_Method' in df_clean.columns and churn_col in df_clean.columns:
    electronic_check_churn = df_clean[df_clean['Payment_Method'] == 'Electronic check'][churn_col].apply(
          lambda x: x == 'Yes'
    ).mean()

    if electronic_check_churn > 0.4:
        recommendations.append({
            'priority': 'HIGH',
            'area': 'Payment Experience',
            'recommendation': 'Improve electronic payment experience',
            'details': f'Electronic check users have {electronic_check_churn:.1%} churn rate. Enhance payment UX and offer auto-pay incentives.',
            'expected_impact': '10-15% churn reduction'
        })

In [69]:
# Tenure-based recommendations
if 'Tenure_Category' in df_clean.columns and churn_col in df_clean.columns:
    new_customer_churn = df_clean[df_clean['Tenure_Category'] == '0-1 Year'][churn_col].apply(
        lambda x: x == 'Yes'
    ).mean()

    if new_customer_churn > 0.4:
        recommendations.append({
            'priority': 'HIGH',
            'area': 'Customer Onboarding',
            'recommendation': 'Enhance new customer onboarding program',
            'details': f'New customers (0-1 year) have {new_customer_churn:.1%} churn rate. Implement 90-day success program.',
            'expected_impact': '20-30% reduction in early churn'
        })

In [70]:
# Service usage recommendations
if 'service_usage_score' in df_clean.columns and churn_col in df_clean.columns:
    low_usage_churn = df_clean[df_clean['service_usage_score'] <= 2][churn_col].apply(
        lambda x: x == 'Yes'
    ).mean()

    if low_usage_churn > 0.3:
        recommendations.append({
            'priority': 'MEDIUM',
            'area': 'Service Adoption',
            'recommendation': 'Increase service adoption through cross-selling',
            'details': f'Low-usage customers have {low_usage_churn:.1%} churn rate. Develop targeted upsell campaigns.',
            'expected_impact': '5-10% churn reduction'
        })

In [74]:
# High-value customer recommendations
if 'customer_value_score' in df_clean.columns and churn_col in df_clean.columns:
    recommendations.append({
        'priority': 'HIGH',
        'area': 'Customer Success',
        'recommendation': 'Implement VIP customer success program',
        'details': 'Create dedicated success managers for high-value customers with proactive engagement.',
        'expected_impact': '25-35% improvement in retention'
        })

In [75]:
# Print recommendations
for i, rec in enumerate(recommendations, 1):
    print(f"\n RECOMMENDATION {i} - {rec['priority']} PRIORITY")
    print(f"Area: {rec['area']}")
    print(f"Recommendation: {rec['recommendation']}")
    print(f"Details: {rec['details']}")
    print(f"Expected Impact: {rec['expected_impact']}")

 RECOMMENDATION 1 - HIGH PRIORITY
Area: Competitive Intelligence
Recommendation: Enhance competitive monitoring and counter-offer programs
Details: 33.2% of churn is due to competitive offers. Implement win-back campaigns and competitive matching.
Expected Impact: 15-25% reduction in competitive churn

 RECOMMENDATION 2 - HIGH PRIORITY
Area: Service Quality
Recommendation: Implement comprehensive service quality improvement program
Details: 21.1% of churn is due to service quality issues. Focus on network improvements and reliability.
Expected Impact: 25-35% reduction in quality-related churn

 RECOMMENDATION 3 - MEDIUM PRIORITY
Area: Customer Support
Recommendation: Enhance customer support experience and training
Details: 10.3% of churn is due to customer support issues. Improve response times and resolution quality.
Expected Impact: 30-40% reduction in support-related churn

 RECOMMENDATION 4 - HIGH PRIORITY
Area: Contract Strategy
Recommendation: Implement contract incentive programs
Details: Month-to-month customers have 42.7% churn rate. Offer discounts for annual contracts.
Expected Impact: 15-25% churn reduction

 RECOMMENDATION 5 - HIGH PRIORITY
Area: Payment Experience
Recommendation: Improve electronic payment experience
Details: Electronic check users have 45.3% churn rate. Enhance payment UX and offer auto-pay incentives.
Expected Impact: 10-15% churn reduction

 RECOMMENDATION 6 - HIGH PRIORITY
Area: Customer Onboarding
Recommendation: Enhance new customer onboarding program
Details: New customers (0-1 year) have 47.7% churn rate. Implement 90-day success program.
Expected Impact: 20-30% reduction in early churn

 RECOMMENDATION 7 - HIGH PRIORITY
Area: Customer Success
Recommendation: Implement VIP customer success program
Details: Create dedicated success managers for high-value customers with proactive engagement.
Expected Impact: 25-35% improvement in retention

#export to excel

In [97]:
df_clean.to_excel('telco_cust_churn_clean.xlsx', index=False)

In [90]:
df_clean.to_csv('telco_cust_churn_clean.csv', index=False)